site_name: Git Docs
theme: mkdocs
pages:
- Git:
    - 'index.md'
    - 'historia.md'
    - 'pra-que-serve.md'
- Comandos: 'comandos.md'
- How To's:
    - 'inicializando-projeto.md'
    - 'criando-historico.md'
    - 'patches.md'
    - 'branches.md'
    - 'merges.md'
    - 'desfazendo.md'
    - 'reescrevendo-historico.md'
    - 'remotos.md'
    - 'ferramentas-auxiliares-e-produtividade.md'
- Recursos Adicionais : 'recursos_adicionais.md'
