site_name: Git Docs
theme: mkdocs
pages:
- Git:
    - Home: 'index.md'
    - História: 'historia.md'
    - Pra que serve: 'pra-que-serve.md'
    - Comandos: 'comandos.md'
- Conceitos: 'conceitos.md'
- How To's:
    - Inicializando um projeto: 'inicializando-projeto.md'
    - Criando Histórico: 'criando-historico.md'
    - Patches: 'patches.md'
    - Branches: 'branches.md'
    - Merges: 'merges.md'
    - Desfazendo: 'desfazendo.md'
    - Remotos: 'remotos.md'
    - Github: 'github.md'
- Avançado:
    - Criando um servidor git: 'criando_servidor.md'
    - Submódulos: 'submodulos.md'
    - Operadores Relativos: 'operadores_relativos.md'
    - Reescrevendo Histórico: 'reescrevendo-historico.md'
    - Debug: 'debug.md'
    - Manutenção: 'manutencao.md'
    - Recuperando dados:  'recuperando_dados.md'
    - Pumbling: 'pumbling.md'
    - Customizando:  'customizando.md'
    - Ferramentas Auxiliares: 'ferramentas-auxiliares-e-produtividade.md'
    - Comandos Menos comuns: 'comandosmenos_comuns.md'
    - Estudos de caso: 'estudos_de_caso.md'
    - Integracoes:  'integracoes.md'
- Recursos Adicionais: 'recursos_adicionais.md'
