site_name: Git Docs
theme: mkdocs
pages:
- Git:
    - Home: 'index.md'
    - História: 'historia.md'
    - Pra que serve: 'pra-que-serve.md'
    - Conceitos: 'conceitos.md'
- Comandos: 'comandos.md'
- How To's:
    - Inicializando um projeto: 'inicializando-projeto.md'
    - Criando Histórico: 'criando-historico.md'
    - Patches: 'patches.md'
    - Branches: 'branches.md'
    - Merges: 'merges.md'
    - Desfazendo: 'desfazendo.md'
    - Remotos: 'remotos.md'
    - Github: 'github.md'
    - Ferramentas Auxiliares: 'ferramentas-auxiliares-e-produtividade.md'
- Avançado:
    - Indice: 'avancado.md'
    - Operadores Relativos: 'operadores_relativos.md'
    - Comparando branches: 'comparando_entre_branches.md'
    - Submódulos: 'submodulos.md'
    - Reescrevendo Histórico: 'reescrevendo-historico.md'
    - Debug: 'debug.md'
    - Comandos Menos comuns: 'comandosmenos_comuns.md'
    - Integracoes:  'integracoes.md'
- Recursos Adicionais: 'recursos_adicionais.md'
